site_name: Documentation de PluXml
site_url: https://www.pluxml.org/
site_description: Documentation de PluXml
site_author: PluXml staff

repo_name: GitHub
repo_url: 'https://github.com/pluxml/PluXml-Wiki'

markdown_extensions:
    - admonition

theme:
    name: mkdocs
    custom_dir: custom_theme/

nav:
- Install: install/installation.md
- Usage: usage/usage.md
- Customize: customize/customization.md
- Develop: develop/develop.md
- Contribute: contribute/contribute.md
- Plugins officiels: divers/plugins-officiels.md
- Plugins non officiels: divers/plugins-non-officiels.md
- Miscellaneous: miscellaneous/miscellaneous-other.md
