site_name: Documentation de PluXml
site_url: https://www.pluxml.org/
site_description: Documentation de PluXml
site_author: PluXml staff

repo_name: GitHub
repo_url: 'https://github.com/pluxml/PluXml-Wiki'

markdown_extensions:
    - admonition

theme:
    name: mkdocs
    custom_dir: custom_theme/

nav:
- Installer: installer/installation.md
- Utiliser: utiliser/utilisation.md
- Personnaliser: personnaliser/personnalisation.md
- Développer: developper/developpement.md
- Contribuer: contribuer/contribuer.md
- Plugins: divers/plugins.md
- Divers: divers/divers-autre.md
